spring.application.name=online-auction-system-backend
server.port=8082
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/online-auction-system
spring.datasource.username=root
spring.datasource.password=Vnav@1790000
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
# JWT secret (use a LONG random secret in production)
app.jwt.secret=Giyu_is_a_water_hashira_the_third_strongest_hashira_water_breathing_11th_form_dead_scilence
# 3 hours in milliseconds
app.jwt.expiration-ms=10800000
