# ---- BUILD STAGE ----
FROM eclipse-temurin:21-jdk AS builder

WORKDIR /app

COPY . .

# build jar
RUN ./mvnw clean package -DskipTests

# ---- RUN STAGE ----
FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8082

ENTRYPOINT ["java", "-jar", "app.jar"]
